
spring:

 mail:
    host: smtp.gmail.com
    username: "khodakhodaieyan@gmail.com"
    password: "MilaD061"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


 eureka:
   instance:
    preferIpAddress: true
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/




